# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Nix Cookbook
tagline:          'Cookbook style to learning Nix expression language for Nix packaging and NixOS'
description:      'by <a href="https://twitter.com/SusanPotter" target="_blank">@SusanPotter</a>.'
url:              https://functionalops.github.io
baseurl:          /nix-cookbook

author:
  name:           'Susan Potter'
  url:            https://twitter.com/SusanPotter

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/functionalops/nix-cookbook
